-- 코드를 입력하세요
SELECT DISTINCT c.CAR_ID, c.CAR_TYPE, ROUND(c.DAILY_FEE * 30 * (100 - d.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON c.CAR_ID = h.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
ON c.CAR_TYPE = d.CAR_TYPE
WHERE (c.CAR_TYPE = "세단" OR c.CAR_TYPE = "SUV")
AND (c.CAR_ID NOT IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-11' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m') AND DATE_FORMAT(END_DATE, '%Y-%m')
    ))
AND (
    d.DURATION_TYPE = "30일 이상" AND ((c.DAILY_FEE * 30 * (100 - d.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000)
)
ORDER BY 3 DESC, 2, 1 DESC