-- 코드를 작성해주세요
SELECT ii.ITEM_ID, ii.ITEM_NAME, ii.RARITY
FROM ITEM_INFO i
JOIN ITEM_TREE t ON i.ITEM_ID = t.PARENT_ITEM_ID
JOIN ITEM_INFO ii ON t.ITEM_ID = ii.ITEM_ID
WHERE i.RARITY = "RARE"
ORDER BY ii.ITEM_ID DESC